import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import {
  ArrowLeft,
  Check,
  ChevronDown,
  Clock3,
  Cpu,
  Download,
  Gauge,
  RotateCcw,
  Sparkles,
  Trash2,
} from "lucide-react";
import { Button } from "../ui/button";
import { Progress } from "../ui/progress";
import { Badge } from "../ui/badge";
import { formatTimestamp } from "@/lib/utils";
import type { RenderPreset } from "@/lib/useLocalStorage";

export default function ProjectHeader({
  title,
  durationSec,
  status,
  progress,
  summary,
  activeStage,
  persona,
  onRerun,
  onReset,
  demoMode,
  source,
  audioCutCount,
  audioScanDone,
  llmMode,
  llmProvider,
  onExport,
  preset,
  onPresetChange,
  exportDisabled,
}: {
  title: string;
  durationSec: number;
  status: "queued" | "processing" | "ready" | "failed";
  progress: number;
  summary?: string;
  activeStage: string;
  persona?: string;
  onRerun: () => void;
  onReset: () => void;
  demoMode: boolean;
  source?: "upload" | "url" | "demo" | "sample";
  audioCutCount?: number;
  audioScanDone?: boolean;
  /** Whether the title/thumbnail stage used a real LLM (e.g. Groq) or fell back to the deterministic pool. */
  llmMode?: "real" | "deterministic";
  /** Friendly label of the LLM provider used (e.g. "groq · llama-3.1-8b-instant"). */
  llmProvider?: string | null;
  /** Real Export hook — receives the project meta. Defaults to a JSON EDL download. */
  onExport?: (edl: ExportArtifact) => void;
  /** Currently-selected libx264 preset — drives the dropdown beside Export. */
  preset?: RenderPreset;
  /** Called when the user picks a different preset; persisted downstream. */
  onPresetChange?: (preset: RenderPreset) => void;
  /** Disable Export + the preset picker while a render is in flight. */
  exportDisabled?: boolean;
}) {
  const isProc = status === "processing";
  const isReady = status === "ready";

  function handleExport() {
    const artifact: ExportArtifact = {
      schema: "neon-edl/v1",
      generatedAt: new Date().toISOString(),
      project: { title, durationSec, status, persona, summary },
    };
    if (onExport) onExport(artifact);
    else defaultExportDownload(artifact);
  }

  return (
    <div className="flex flex-wrap items-end justify-between gap-4 border-b border-border/60 px-5 py-4">
      <div className="min-w-0 flex-1">
        <Link
          to="/dashboard"
          className="inline-flex items-center gap-1 text-xs text-muted-foreground transition hover:text-foreground"
        >
          <ArrowLeft className="h-3 w-3" /> Studio · projects
        </Link>
        <div className="mt-1 flex flex-wrap items-center gap-3">
          <h1 className="line-clamp-1 text-2xl font-semibold tracking-tight md:text-3xl">
            {title}
          </h1>
          <Badge variant="outline" className="border-border/80 text-muted-foreground">
            <Clock3 className="mr-1 h-3 w-3" /> {formatTimestamp(durationSec)}
          </Badge>
          {persona && (
            <Badge variant="outline" className="border-primary/40 text-primary">
              {persona}
            </Badge>
          )}
          {source === "upload" && audioScanDone && (
            <Badge variant="outline" className="border-accent/40 bg-accent/10 text-accent">
              Real audio scan · {audioCutCount ?? 0} cuts
            </Badge>
          )}
          {source === "upload" && !audioScanDone && (
            <Badge variant="outline" className="border-primary/40 bg-primary/10 text-primary">
              Real analysis · browser-side
            </Badge>
          )}
          {llmMode === "real" && llmProvider?.includes("fixture") && (
            <Badge
              variant="outline"
              className="border-accent/60 bg-accent/10 text-accent"
              data-testid="badge-llm-fixture"
              title={`Metric-driven fixture (GROQ_DEMO_MODE=simulate). No API call was made.`}
            >
              <Sparkles className="mr-1 h-3 w-3" />
              Demo · simulated narrative
              <span className="ml-1.5 hidden text-[10px] sm:inline">
                (GROQ_DEMO_MODE)
              </span>
            </Badge>
          )}
          {llmMode === "real" && !llmProvider?.includes("fixture") && (
            <Badge
              variant="outline"
              className="border-primary/60 bg-primary/10 text-primary"
              data-testid="badge-llm-real"
              title={`Titles + headlines were generated by ${llmProvider ?? "a real LLM"}`}
            >
              <Sparkles className="mr-1 h-3 w-3" />
              Real LLM narrative · {capitalizeProvider(llmProvider ?? "groq")}
            </Badge>
          )}
          {llmMode === "deterministic" && (
            <Badge
              variant="outline"
              className="border-border/80 text-muted-foreground"
              data-testid="badge-llm-deterministic"
              title="Add GROQ_API_KEY in the project keys tab to enable real LLM titles."
            >
              Pool · no LLM key
              <span className="ml-1.5 hidden text-[10px] sm:inline">
                (add GROQ_API_KEY)
              </span>
            </Badge>
          )}
          {demoMode && source !== "upload" && (
            <Badge variant="outline" className="border-accent/40 text-accent">
              Demo · simulated pipeline
            </Badge>
          )}
        </div>
        <div className="mt-3 flex flex-wrap items-center gap-3">
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <Cpu className="h-3.5 w-3.5 text-primary" />
            <span>{activeStage || (isReady ? "Idle" : "Starting…")}</span>
          </div>
          <div className="min-w-[180px] max-w-[320px] flex-1">
            <Progress value={progress} />
          </div>
          <span className="font-mono text-xs text-muted-foreground">
            {progress}%
          </span>
          {summary && (
            <span className="line-clamp-1 max-w-[420px] text-xs text-muted-foreground">
              {summary}
            </span>
          )}
          {isProc && (
            <motion.span
              className="ml-1 inline-block h-2 w-2 rounded-full bg-primary"
              animate={{ opacity: [0.3, 1, 0.3] }}
              transition={{ duration: 1.6, repeat: Infinity }}
            />
          )}
        </div>
      </div>
      <div className="flex items-center gap-2">
        <Button variant="ghost" onClick={onRerun} className="gap-1.5">
          <RotateCcw className="h-4 w-4" /> Re-run
        </Button>
        <Button variant="ghost" onClick={onReset} className="gap-1.5">
          <Trash2 className="h-4 w-4 text-destructive" /> Reset
        </Button>
        {preset && onPresetChange && (
          <PresetPicker
            value={preset}
            onChange={onPresetChange}
            disabled={exportDisabled || !isReady}
          />
        )}
        <Button
          disabled={!isReady || exportDisabled}
          onClick={handleExport}
          className="bg-primary text-primary-foreground hover:bg-primary/90"
          data-testid="export-button"
        >
          <Download className="h-4 w-4" /> Export
        </Button>
      </div>
    </div>
  );
}

export type ExportArtifact = {
  schema: "neon-edl/v1";
  generatedAt: string;
  project: {
    title: string;
    durationSec: number;
    status: string;
    persona?: string;
    summary?: string;
  };
};

function defaultExportDownload(artifact: ExportArtifact) {
  const json = JSON.stringify(artifact, null, 2);
  const blob = new Blob([json], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  const safe = artifact.project.title.replace(/[^a-z0-9-_ ]/gi, "").trim() || "neon-edit";
  a.download = `${safe}.neon-edl.json`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * Inline preset dropdown used next to the Export button. We build
 * this ourselves (no extra dependency) because:
 *   - shadcn/ui has no Select in this project yet — we'd be the
 *     first user, and adding `@radix-ui/react-select` for one tiny
 *     dropdown feels disproportionate.
 *   - The popover only ever renders 4 fixed options, so the
 *     accessibility surface (aria-haspopup / aria-expanded /
 *     role=listbox / role=option) is small enough that a hand-rolled
 *     version reads cleanly.
 */
function PresetPicker({
  value,
  onChange,
  disabled,
}: {
  value: RenderPreset;
  onChange: (v: RenderPreset) => void;
  disabled?: boolean;
}) {
  const [open, setOpen] = useState(false);
  const wrapRef = useRef<HTMLDivElement | null>(null);

  // Click-outside dismissal — keep the popover focused only while it's open.
  useEffect(() => {
    if (!open) return;
    function onDocDown(e: MouseEvent) {
      if (!wrapRef.current) return;
      if (!wrapRef.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener("mousedown", onDocDown);
    return () => document.removeEventListener("mousedown", onDocDown);
  }, [open]);

  // Per-option labels + brief size/time hints. Sizes are rough H.264
  // averages for 720p30 content with -preset <name> — real-world
  // varies ±30% with scene complexity. Tune the numbers if you ship
  // a different resolution profile (1080p averages ~2.4× these).
  const OPTIONS: ReadonlyArray<{
    value: RenderPreset;
    label: string;
    hint: string;
  }> = [
    { value: "ultrafast", label: "Fastest", hint: "~5 MB/min" },
    { value: "superfast", label: "Fast", hint: "~3 MB/min · 2× encode" },
    { value: "veryfast", label: "Balanced", hint: "~2 MB/min · 4× encode" },
    { value: "medium", label: "Smallest file", hint: "~1.5 MB/min · 10× encode" },
  ];
  const current = OPTIONS.find((o) => o.value === value) ?? OPTIONS[0];

  return (
    <div ref={wrapRef} className="relative">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        disabled={disabled}
        aria-haspopup="listbox"
        aria-expanded={open}
        data-testid="preset-trigger"
        className="inline-flex items-center gap-1.5 rounded-md border border-border/70 bg-secondary/60 px-2.5 py-1.5 text-xs font-medium text-foreground transition-colors hover:bg-secondary disabled:cursor-not-allowed disabled:opacity-50"
      >
        <Gauge className="h-3.5 w-3.5 text-muted-foreground" />
        <span>
          Preset · <span className="text-primary">{current.label}</span>
        </span>
        <ChevronDown className="h-3 w-3 text-muted-foreground" />
      </button>
      {open && (
        <div
          role="listbox"
          className="absolute right-0 z-50 mt-1.5 w-60 overflow-hidden rounded-lg border border-border/70 bg-popover text-popover-foreground shadow-xl"
        >
          {OPTIONS.map((opt) => {
            const selected = opt.value === value;
            return (
              <button
                type="button"
                key={opt.value}
                role="option"
                aria-selected={selected}
                data-testid={`preset-option-${opt.value}`}
                onClick={() => {
                  onChange(opt.value);
                  setOpen(false);
                }}
                className={
                  "flex w-full flex-col items-start gap-0.5 px-3 py-2 text-left text-xs transition-colors hover:bg-accent/30 " +
                  (selected
                    ? "bg-primary/10 text-primary"
                    : "")
                }
              >
                <span className="flex w-full items-center justify-between">
                  <span className="font-medium">{opt.label}</span>
                  <Check
                    className={
                      "h-3 w-3 transition-opacity " +
                      (selected ? "opacity-100" : "opacity-0")
                    }
                  />
                </span>
                <span className="text-[10px] text-muted-foreground">
                  {opt.hint}
                </span>
              </button>
            );
          })}
        </div>
      )}
    </div>
  );
}

/**
 * Title-case the provider segment so the badge reads "Groq" instead of
 * "groq" (the wire format is lowercase). Capitalizes the first character
 * of the first word only, leaving the model segment untouched
 * (`llama-3.1-8b-instant` stays lowercase).
 */
function capitalizeProvider(provider: string): string {
  const space = provider.indexOf(" ");
  if (space < 0) {
    return provider.charAt(0).toUpperCase() + provider.slice(1);
  }
  const first = provider.slice(0, space);
  const rest = provider.slice(space);
  return first.charAt(0).toUpperCase() + first.slice(1) + rest;
}
